Suggest capitalized SPARQL keywords
stardog-union/stardog-language-servers pull request #26
Opened 2019-09-12 18:03 UTC by anneeb

dependent on https://github.com/stardog-union/millan/pull/38

2019-09-12 18:30 UTC, jmrog commented on packages/sparql-language-server/src/SparqlLanguageServer.ts
> +      ).toUpperCase();
This is a small point in the overall scheme of things, but: I noticed that `regexPatternToString` has a `toLowerCase` call in it. So, we're doing `toLowerCase()` --> `toUpperCase()` now. On a quick look, it looks like `regexPatternToString` is used _only_ for SPARQL tokens (where we want things uppercase) and in one other case, for SHACL completion. In the latter case, I don't think we actually even _want_ to be using it (SHACL completion is buggy right now because it shows gigantic regexes when we don't really want them). In other words, I think SHACL should probably not do this:

```
    if (!isStringPattern && !(pattern instanceof RegExp)) {
      // This token uses a custom pattern-matching function and we therefore
      // cannot use its pattern for autocompletion.
      return;
    }

    const completionString = isStringPattern
      ? pattern
      : regexPatternToString(pattern)
```

It should probably instead only return the completions that are string patterns (at least for now). So, could we just remove the `toLowerCase` from `regexPatternToString`, _not_ do the `toUpperCase` here, and remove the use of `regexPatternToString` in SHACL (either now or as a separate PR?). My suspicion is that we'll get what we want and not be doing `toLowerCase()` --> `toUpperCase()` anymore.

2019-09-12 20:21 UTC, anneeb commented on packages/sparql-language-server/src/SparqlLanguageServer.ts
> +      ).toUpperCase();
Ooh. I also realized that not all the keywords _should_ be all uppered or lowered, that is there are some that are cameled (`isIRI` and `isBlank`) and we should probably just always use whatever cases the regex pattern is originally written as.

2019-09-13 13:24 UTC, jmrog requested changes
See comment.

2019-09-13 13:24 UTC, jmrog commented on packages/turtle-language-server/__tests__/integration.test.ts
> +            "\tExpected one of the following:\n IRIREF\n PNAME_LN\n PNAME_NS\n BLANK_NODE_LABEL\n ANON e.g. []\n '('\n '['\n STRING_LITERAL_QUOTE\n STRING_LITERAL_SINGLE_QUOTE\n STRING_LITERAL_LONG_S
Hm, this is actually no good (for the booleans); Turtle is case-sensitive. See, for example, rule 5 [here](https://www.w3.org/TR/turtle/#sec-diff-sparql) or note 1 [here](https://www.w3.org/TR/turtle/#sec-grammar-grammar).

2019-09-13 13:48 UTC, anneeb commented on packages/turtle-language-server/__tests__/integration.test.ts
> +            "\tExpected one of the following:\n IRIREF\n PNAME_LN\n PNAME_NS\n BLANK_NODE_LABEL\n ANON e.g. []\n '('\n '['\n STRING_LITERAL_QUOTE\n STRING_LITERAL_SINGLE_QUOTE\n STRING_LITERAL_LONG_S
Okay. Turtle should probably have its own tokens for booleans then since the SPARQL ones it's currently using are case insensitive.

2019-09-13 20:24 UTC, jmrog approved these changes
LGTM

2019-09-13 20:24 UTC, merged